openpathsampling/openpathsampling-cli

- .travis.yml
- README.md
- paths_cli/commands/append.py
- setup.cfg
Releases in the 0.0.x sequence are for debugging our [automated release process](https://github.com/dwhswenson/autorelease/).
> Release 0.0.1

- paths_cli/cli.py
- paths_cli/tests/null_command.py
- paths_cli/tests/test_cli.py
This will add the `--log` option, which takes a Python logging configuration file, to the main command. 
Usage would be like this:
```
openpathsampling --log logging.conf pathsampling setup.nc -o output.nc -n 1000
```
Note that the `--log` option comes *before* the command.
> Add --log (logging conf) option to main command

- devtools/miniconda_install.sh
- paths_cli/cli.py
- paths_cli/plugin_management.py
- paths_cli/tests/null_command.py
- paths_cli/tests/test_cli.py
- paths_cli/tests/test_plugin_management.py
- setup.cfg
This new approach will include two different ways to create OPS plugins. The key difference is in how plugins are discovered:
1. "File plugins": This is the same functionality that has already been implemented: search specific directories for files that can be used as plugins.
2. "Namespace package plugins": This approach is basically described in https://packaging.python.org/guides/creating-and-discovering-plugins/#using-namespace-packages. We'll expect [native namespace packages](https://packaging.python.org/guides/packaging-namespace-packages/#native-namespace-packages).
"File plugins" are suitable as a quick-and-dirty approach for yourself or for small-scale sharing. "Namespace package plugins" take a little more work, but are more suitable to be widely distributed.
This PR will …
> Update plugin management approach

- .github/workflows/test-suite.yml
This is also a way of testing whether changes to workflows from forks will work, or if I can only make those changes from the main repo.
UPDATE: It looks like the answer to that is yes -- so apparently I won't run a new workflow added in a PR from a fork, but I can edit an existing workflow as part of a PR from a fork.
> Fix typo in actions

- paths_cli/commands/equilibrate.py
- paths_cli/param_core.py
- paths_cli/parameters.py
- paths_cli/tests/commands/test_pathsampling.py
- paths_cli/tests/test_parameters.py
This PR enables multiple usage of the `--init-conds` flag, so that a user can select multiple initial trajectories to be used as the potential sources of initial conditions.
> Allow multiple uses of --init-conds

- paths_cli/commands/contents.py
- paths_cli/tests/commands/test_contents.py
This allows users to only load a specific table with the `contents` subcommand. Not only does this allow one to cut down on clutter, but there are some tables that are not shown in the normal `contents` command. Example:
```
$ openpathsampling contents mstis.nc --table ensembles
Storage @ '/Users/dwhs/ops_tutorial/mstis.nc'
ensembles: 218 items
* Out A 0
* Out A 2
* Out B 1
* Out B 2
* Out C 0
* Out C 2
* Out C 1
* Out B 0
* Out A 1
* Out A minus
* Out B minus
* Out C minus
* plus 206 unnamed items
```
> Add  --table option in `contents`

- README.md
- paths_cli/commands/md.py
- paths_cli/commands/visit_all.py
- paths_cli/parameters.py
- paths_cli/tests/commands/test_md.py
- paths_cli/utils.py
This adds a new `md` subcommand, which allows a user to run normal MD using the given engine. This can be used with either the `--nsteps` parameter to run a specific number of steps, or (perhaps more interestingly) with the `--ensemble` parameter to create a trajectory that contains a subtrajectory satisfying the ensemble.
The `--ensemble` option can be given more than once. The resulting trajectory will have subtrajectories that satisfy each of the provided ensembles.
> New command: `md`

- .github/workflows/test-suite.yml
- docs/plugins.rst
- paths_cli/cli.py
- paths_cli/plugin_management.py
The previous implementation of namespace plugins didn't actually work with namespace plugins. This PR fixes it (tested against an actual external plugin).
> Fix up namespace plugins

- paths_cli/tests/test_parameters.py
Changes related to CVs being imported at `openpathsampling.collectivevariables` instead of `.collectivevariable` meant that if you patch and unpatch to support SimStore, you get the same base classes defined at two different memory addresses, which caused non-obvious problems when calling `super`. This PR fixes.
This is only an issue for situations like unit tests, where it is necessary to unpatch for SimStore after patching.
> Fix tests for moved CVs in OPS 1.5

- docs/plugins.rst
- example_plugins/one_pot_tps.py
- example_plugins/tps.py
- paths_cli/__init__.py
- paths_cli/cli.py
- paths_cli/commands/append.py
- paths_cli/commands/contents.py
- paths_cli/commands/equilibrate.py
- paths_cli/commands/md.py
- paths_cli/commands/pathsampling.py
- paths_cli/commands/visit_all.py
- paths_cli/param_core.py
- paths_cli/plugin_management.py
- paths_cli/tests/null_command.py
- paths_cli/tests/test_cli.py
- paths_cli/tests/test_plugin_management.py
This PR introduces a new plugin infrastructure for the OPS CLI. This is a major API break, and all externally-developed plugins will need to update for it.
Fortunately, the update procedure is simple: Previously, plugins had to be one per module (file), and the modules needed to define the variables `CLI` (to label the command), `SECTION` (the help section to use), and optionally `REQUIRES_OPS` (the minimum OPS version).
The new plugins require importing `paths_cli.OPSCommandPlugin`, and then creating an `OPSCommandPlugin` instance, which takes the required variables `command` and `section`, and the optional variables `requires_ops` and `requires_cli` (which defines the minimum CLI version.) Note that this `OPSCommandPlugin` instance must be assigned to a name in the module (it needs to …
> New plugin infrastructure

- paths_cli/tests/wizard/conftest.py
- paths_cli/tests/wizard/test_openmm.py
- paths_cli/wizard/openmm.py
Most significantly, this fixes a test error on the URL [that @sroet suggested I add a test for](https://github.com/openpathsampling/openpathsampling-cli/pull/41#discussion_r676509042) (thanks @sroet!) by removing the `simtk` from the URL. I also went ahead and made it so we preferred new 7.6-style imports everywhere else.
> Updates for OpenMM 7.6

- paths_cli/commands/contents.py
- paths_cli/parameters.py
Files can also be .db. Change recommended as an aside in https://github.com/openpathsampling/mini-tutorials/issues/5#issuecomment-911562562.
> Remove nc from descriptions of OPS files

- .github/workflows/test-suite.yml
[codecov deprecated the bash uploader](https://about.codecov.io/blog/codecov-uploader-deprecation-plan/). They advice people to switch to [their github action workflow](https://github.com/marketplace/actions/codecov). This implements the suggested switch
> switch codecov bash uploader for their github action

- .github/workflows/test-suite.yml
- setup.cfg
Technically, we could drop this as of June 23, 2020, since we're following NEP 29 here. However, there was no need until I started working on #54, where I want defaults in a `namedtuple` (introduced in Python 3.7).
Not adding Python 3.10 to the test matrix yet because we're waiting on support from our requirements (which, y'know, starts with conda-forge having Python 3.10 available.)
> Drop Python 3.6 support

- paths_cli/compiling/core.py
- paths_cli/compiling/cvs.py
- paths_cli/compiling/engines.py
- paths_cli/compiling/errors.py
- paths_cli/compiling/networks.py
- paths_cli/compiling/plugins.py
- paths_cli/compiling/root_compiler.py
- paths_cli/compiling/schemes.py
- paths_cli/compiling/shooting.py
- paths_cli/compiling/strategies.py
- paths_cli/compiling/tools.py
- paths_cli/compiling/topology.py
- paths_cli/compiling/volumes.py
Now that my in-editor linter is working again, I went over the code in the `compiling` subpackage and cleaned up most of the things that registered as errors in `pylint` and `flake8`.
I also used this as an excuse to start writing up a more detailed style guide for OpenPathSampling projects. I plan to put it in the main OPS developer docs as part of OPS 2.0 (it is Python 3 specific). The document is basically a list of "here are common cases where we allow exceptions to flake8/pylint errors and warnings" (basically, some guidelines as to when, IMHO, consistency becomes foolish consistency.)
Doc being developed in a gist: https://gist.github.com/dwhswenson/1361b849866af98e7f8e6599810670b2
EDIT: also includes an incorrect version requirement in `CategoryPlugin`, which will be part of v0.3 …
> pylint/flake8: `paths_cli.compiling`

- paths_cli/tests/wizard/test_wizard.py
- paths_cli/wizard/wizard.py
This adds support for the `!quit` (or `!q`) command in the wizard to give the option to save objects created so far to a file. This has been the intent: `!!quit` is an immediate force-quit; `!quit` quits the wizard process early with the option to save.
This is one of the targets for v0.3 listed in #57:
- Add support for catching the quit exception when the wizard is running
> Wizard: `!quit` command should give option to save

- paths_cli/tests/test_utils.py
- paths_cli/utils.py
As mentioned in #57, the Wizard would benefit from plugins always loading in the same order. Without this, the order of category plugins located in the same file tended to be random. For example, the choices of CV types (Distance, Angle, Dihedral, etc) were not consistent between different runs of the wizard. This also seemed to be the case with command plugins: the order they were listed in `--help` was not retained.
Here I replace the `set` used previously with a custom-written `OrderedSet` class. This seems to have fixed these consistency issues.
> Preserve plugin load order with `OrderedSet`

- paths_cli/tests/wizard/test_wizard.py
- paths_cli/wizard/wizard.py
Previously, if the user input was the empty string, the code checking for help/command (looking are `user_input[0]` would error out. This prevents that error from occurring.
> Wizard: Fix uncaught exception if user input is empty

- paths_cli/tests/wizard/conftest.py
- paths_cli/tests/wizard/mock_wizard.py
- paths_cli/tests/wizard/test_pause.py
- paths_cli/tests/wizard/test_volumes.py
- paths_cli/wizard/pause.py
- paths_cli/wizard/two_state_tps.py
- paths_cli/wizard/volumes.py
- paths_cli/wizard/wizard.py
This PR will address the need for pauses in the wizard. Currently, the wizard hops from one step to the next very quickly; a brief pause (and possibly some visual cues) will improve UX by making it easier to track what is happening.
This addresses one of the targets for before v0.3 raised in #57:
* Add pauses at various points to give better UX
* creating subvolumes
* after naming an object
Tasks
> Wizard pauses

- paths_cli/tests/wizard/test_load_from_ops.py
- paths_cli/wizard/core.py
- paths_cli/wizard/cvs.py
- paths_cli/wizard/engines.py
- paths_cli/wizard/errors.py
- paths_cli/wizard/helper.py
- paths_cli/wizard/joke.py
- paths_cli/wizard/load_from_ops.py
- paths_cli/wizard/openmm.py
- paths_cli/wizard/parameters.py
- paths_cli/wizard/plugin_classes.py
- paths_cli/wizard/plugin_registration.py
- paths_cli/wizard/run_module.py
- paths_cli/wizard/shooting.py
- paths_cli/wizard/standard_categories.py
- paths_cli/wizard/steps.py
- paths_cli/wizard/tools.py
- paths_cli/wizard/tps.py
- paths_cli/wizard/two_state_tps.py
- paths_cli/wizard/wizard.py
This performs the pylint/flake8 cleanup for the `wizard` subpackage requested in #57. Mainly this involved removing some unused imports and unused code and adding a lot of docstrings.
The Wizard API is still expected to be in a state of rapid flux (even after the v0.3 release) so some parameters that are likely to be removed are not always documented, and some methods that are likely to be removed are only partly documented. I also marked a few things as likely to change in the near future.
Code style exceptions to pylint/flake8 rules here: https://gist.github.com/dwhswenson/1361b849866af98e7f8e6599810670b2
> pylint/flake8: `paths_cli.wizard`

- paths_cli/compiling/_gendocs/docs_generator.py
- paths_cli/compiling/_gendocs/json_type_handlers.py
- paths_cli/compiling/cvs.py
- paths_cli/compiling/engines.py
- paths_cli/compiling/gendocs.py
- paths_cli/compiling/json_type.py
- paths_cli/compiling/networks.py
- paths_cli/compiling/plugins.py
- paths_cli/compiling/root_compiler.py
- paths_cli/compiling/schemes.py
- paths_cli/compiling/shooting.py
- paths_cli/compiling/strategies.py
- paths_cli/compiling/tools.py
- paths_cli/compiling/volumes.py
- paths_cli/tests/compiling/test_root_compiler.py
This PR will clean up the `compiling` subpackage such that the `gendocs` script creates complete and suitable documentation for the built-in plugins. This primarily involves adding descriptions and type information.
> Fill in information for `compile` docs

- .coveragerc
- paths_cli/compiling/core.py
- paths_cli/tests/commands/test_md.py
- paths_cli/tests/commands/utils.py
- paths_cli/tests/compiling/test_core.py
- paths_cli/tests/compiling/test_volumes.py
- paths_cli/tests/test_file_copying.py
- paths_cli/tests/test_parameters.py
- paths_cli/tests/test_utils.py
- paths_cli/tests/utils.py
- paths_cli/tests/wizard/mock_wizard.py
- paths_cli/tests/wizard/test_load_from_ops.py
- paths_cli/tests/wizard/test_parameters.py
- paths_cli/tests/wizard/test_volumes.py
- paths_cli/tests/wizard/test_wizard.py
Back in March, I saw a tweet from Ned Batchelder linking to this:
https://nedbatchelder.com/blog/202008/you_should_include_your_tests_in_coverage.html
Since then, I've been considering including test suites in coverage. This PR adds the test suite to the coverage data. Consider this a proposal, because I'm not necessarily wedded to the idea we have to do this. But please read Ned's blog post, and consider if doing this affects your workflow in any way.
My own thoughts on the concerns Ned's post mentions:
* **It skews my results**: This is part of why I don't do it on the OPS library (because we should be ashamed of low coverage! 80% is shame in a way 90% is not!) However, on packages that already have 100% coverage, there's nothing to skew -- so I'm in favor of including tests in coverage …
> Stop excluding tests from coverage

- paths_cli/commands/contents.py
- paths_cli/tests/commands/test_contents.py
This is a better solution for #71 (should replace #72).
We really don't want all that junk in the `contents` output anyway. The purpose of that line to give the filename as part of the output, so let's just give the filename.
> Fix error in output for contents

- .github/workflows/test-suite.yml
- paths_cli/tests/commands/test_md.py
- paths_cli/tests/compiling/_gendocs/test_docs_generator.py
- paths_cli/tests/compiling/test_core.py
- paths_cli/tests/compiling/test_cvs.py
- paths_cli/tests/compiling/test_engines.py
- paths_cli/tests/compiling/test_plugins.py
- paths_cli/tests/compiling/test_root_compiler.py
- paths_cli/tests/compiling/test_volumes.py
- paths_cli/tests/test_cli.py
- paths_cli/tests/test_file_copying.py
- paths_cli/tests/test_parameters.py
- paths_cli/tests/test_plugin_management.py
- paths_cli/tests/test_utils.py
- paths_cli/tests/wizard/test_helper.py
- paths_cli/tests/wizard/test_parameters.py
- paths_cli/tests/wizard/test_plugin_classes.py
- paths_cli/tests/wizard/test_wizard.py
Problems with CI that this will fix:
1. We're way behind on Python versions; this brings the CLI in line with versions tested in the OPS library
2. We're having a problem with the build process; seems something was problematic with the pip install stack (I think this was fixed by not trying to support older Pythons)
4. Tests needed to be updated from `setup`/`teardown` to `setup_method`/`teardown_method`
5. Updated CodeCov, as it didn't seem to allow uploads without token.
This wasn't as bad as I feared!
> Fix CI problems

- LICENSE
- README.md
Apparently our CI badge here is out of date, and therefore giving bad status. Also, the copyright notice needed to be touched.
Should have no effect on code. I'll merge on green; don't see a need for review on this.
> Update badge; copyright in LICENSE

- paths_cli/cli.py
- paths_cli/commands/compile.py
- paths_cli/compiling/_gendocs/docs_generator.py
- paths_cli/tests/compiling/_gendocs/test_docs_generator.py
I'm going to leave the wizard hidden for the 0.3 release, but compile is one of the marquee features for this release.
To-do:
- ~Needs to link to the page in core docs that discusses default options and how to generate documentation for all installed options.~
EDIT: To clarify here, I have made the decision that the Wizard, while a lot of fun, isn't mature enough or well-designed enough to be something I want to commit to maintaining. It also isn't an approach that we should put much effort into expanding/maturing (there are better ways to be user friendly.) It was originally a bit of a response to people who kept saying that OPS was too hard to use because it required working in a Jupyter notebook. Frankly, I think there are better solutions to make that response.
However, I totally …
> Add help to compile; make it visible in CLI help

- .github/workflows/test-suite.yml
- paths_cli/tests/compiling/test_root_compiler.py
- paths_cli/tests/wizard/test_plugin_classes.py
Both [SPEC0](https://scientific-python.org/specs/spec-0000/) and [NEP29](https://numpy.org/neps/nep-0029-deprecation_policy) currently recommend supporting Python versions 3.10, 3.11, and 3.12. Tests here hadn't started on 3.12 and still tested 3.9. This PR just changes the testing matrix.
> SPEC0/NEP29: Add Python 3.12, drop Python 3.9

- paths_cli/cli.py
On importing OpenMMTools (which happens as part of reloading objects), we get some annoying warnings from pymbar. I'd like to try to get this fixed upstream in OpenMMTools, but for now here's a hack that makes it less unpleasant to work with the CLI.
> Silence annoying pymbar warnings

- setup.cfg
This is a minor update to fix a bug in packaging.
* Add `compat/__init__.py` ([#82](https://github.com/openpathsampling/openpathsampling-cli/pull/82))
> Release 0.3.1

- setup.cfg
This should have been added in 0.3.0, with the compiling subpackage. It has been (and probably will be) fine as a transitive dependency from OpenPathSampling. But there's no reason not to do best practices.
See https://github.com/conda-forge/openpathsampling-cli-feedstock/pull/7#issuecomment-2277019583
> Add numpy as req in setup.cfg

- paths_cli/commands/load_trajectory.py
- paths_cli/tests/commands/test_load_trajectory.py
This will give a convenience for loading an existing trajectory from an external file into an OPS file.
Although it is loading into the OpenMM snapshot format, this is mainly because that is internally stored. We should be able to write out to most MD-based engines based on that internal format.
TODO:
> New command: Load trajectory

- paths_cli/parameters.py
- paths_cli/tests/commands/test_equilibrate.py
- paths_cli/tests/commands/test_pathsampling.py
- paths_cli/tests/test_parameters.py
This changes the result of the `INIT_CONDS.get()` method so that it always returns a list of a trajectories. Since this is usually then consumed by `scheme.initial_conditions_from_trajectories`, this approach will always give a workable result. This is an API break, but since the result on the typical consumer is to allow more input types, I'm not concerned with backward compatibility.
The issue was that sometimes, if calling the `INIT_CONDS` parameter multiple times (e.g., `SampleSet` or `Trajectory` objects from different interface sets/interfaces), this would break the input of `scheme.initial_conditions_from_trajectories`. While it might be good to also modify that function to allow multiple `SampleSet`s and a mixture of types in the input list, it seemed easier to make that change in …
> Convert output of `INIT_CONDS` parameter to list of trajectories

- paths_cli/commands/bootstrap_init.py
- paths_cli/parameters.py
- paths_cli/tests/commands/test_bootstrap_init.py
- paths_cli/tests/conftest.py
This provides a CLI interface for the `FullBootstrap` initialization from OpenPathSampling core, which is used in the MSTIS/MISTIS OPS example notebooks.
> New command: `bootstrap-init`
